/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"
#include "switch.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
   // Initialize the system clock and configuration
   SystemInit();

   // Counter to keep track of which LED to blink
   uint32_t count = 0;

   // Base pin (LED_GREEN_PIN assumed to be a macro defined in led.h)
   uint32_t pin = LED_GREEN_PIN;

   // Initialize all 4 LEDs (assuming each LED has a unique pin defined in led.h)
   led_init(LED_ORANGE_PIN);
   led_init(LED_GREEN_PIN);
   led_init(LED_BLUE_PIN);
   led_init(LED_RED_PIN);

   // Initialize the switch
   SwitchInit();

	while(1)
	{
		    // Wait until the switch is pressed (switch_flag set by interrupt or polling in switch.c)
            while(switch_flag == 0);

            // Blink the corresponding LED for 500ms ("pin + count" calculates the current LED pin)
            ledblink(pin + count , 500);

            // Move to the next LED
            count++;

            // Reset the switch flag so the loop waits for the next press
            switch_flag = 0;

            if(count == 4)
            {
            	// Restart from the first LED after blinking all 4
            	count = 0;
            }
	}
	return 0;
}
