/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Initialize the system clock and configuration
	SystemInit();

	// Enable clock for GPIOD (GPIO port D)
	RCC -> AHB1ENR |= BV(3);

	// Configure GPIOD pin 13 as an output
	GPIOD -> MODER &= ~BV(27);	// Clear mode for pin 13
	GPIOD -> MODER |= BV(26);	// Set mode for pin 13

	// Set pin 13 output type as open-drain
	GPIOD -> OTYPER |= BV(13);

	// Configure the output low speed for pin 13
	GPIOD -> OSPEEDR &= ~(BV(27));
	GPIOD -> OSPEEDR |= (BV(26));

	// Configure pull-up/pull-down resistor for pin 13
	GPIOD -> PUPDR &= ~BV(27);
	GPIOD -> PUPDR |= BV(26);

	while(1)
	{
		// Set pin 13 to high (turn ON the LED connected to pin 13)
		GPIOD -> ODR |= BV(13);
		DelayMs(500);

		// Set pin 13 to low (turn OFF the LED connected to pin 13)
		GPIOD -> ODR &= ~BV(13);
		DelayMs(500);
	}

	return 0;
}
